FROM nvidia/cuda:12.6.3-base-ubuntu24.04

RUN apt-get update -y && \
	apt-get install -y wget git python3 python3-pip python3-venv libgl1 libglib2.0-0 neovim software-properties-common && \
	apt-add-repository -y ppa:deadsnakes/ppa && \
	apt-get update -y && \
	apt-get install -y python3.11 python3.11-venv && \
	adduser --disabled-password --gecos '' user && \
	mkdir /stablediffusion && \
	chown -R user:user /stablediffusion

WORKDIR /stablediffusion
USER user

RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui /stablediffusion && \
	cd /stablediffusion && \
	git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui && \
	sed -i -e 's/#python_cmd=\"python3\"/python_cmd=\"python3.11\"/g' webui-user.sh && \
	curl https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors -P /stablediffusion/models/Stable-diffusion/ && \
	./webui.sh
	
